feat: Реализована функция удаления фильма и пользователя по id
Elite-tea/java-filmorate pull request #10
Opened 2023-08-30 06:00 UTC by Elite-tea

fix: Добавлен доступ к хранилищу фильмов из сервиса фильмов
fix: Исправлена документация некоторых методов
delete: Удалены неиспользуемые методы

2023-08-30 07:58 UTC, Chernosmaga commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @DeleteMapping("{id}")
маппинг должен быть следующего формата: @DeleteMapping("/{id}"), потому что слэш указывается в начале эндпоинта

2023-08-30 07:58 UTC, Chernosmaga commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @DeleteMapping("{userId}")
Та же самая ситуация :)

2023-08-30 08:00 UTC, Chernosmaga commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/film/FilmDbStorage.java
>              throw new NotFoundException(String.format("Фильма с id %d не существует", filmId));
Я когда рефакторил тебе код нашёл много ошибок форматирования текста. %d - для demicial, а %s - для string, не забывай :)

2023-08-30 08:03 UTC, Chernosmaga requested changes
Торопишься, видимо, поэтому делаешь мелкие ошибки. Не спеши, у нас ещё много времени ;)

2023-08-30 13:10 UTC, MaksSyrnev reviewed
привет. оставил комментарии

2023-08-30 13:10 UTC, MaksSyrnev commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/film/FilmDbStorage.java
> +        if (!getByIdFilm(id).getName().isEmpty()) {
нужна ли  тут эта проверка?  лишний запрос к базе

2023-08-30 13:10 UTC, MaksSyrnev commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/film/FilmDbStorage.java
> +            jdbcTemplate.update("DELETE FROM film WHERE film_id = ?",id);
update возвращает количество обновленных строк, соответственно можно смотреть на это число - 0 - не найден такой фильм,  1- все ок, удален, больше 1 - тут что то пошло не так.

2023-08-30 13:10 UTC, MaksSyrnev commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/film/FilmDbStorage.java
> +            jdbcTemplate.update("DELETE FROM film WHERE film_id = ?",id);
сам запрос -"DELETE FROM film WHERE film_id = ?" можно вынести в константу. на усмотрение, мне так подсказали сделать, потому что бывают запросы очень длинные, и их не удобно в методе читать.

2023-08-30 13:10 UTC, MaksSyrnev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        filmService.getFilmStorage().deleteFilm(id);
на мой взгляд, вот тут слишком нагружено, читать тяжело, мне минут 5 потребовалось пока я допер, что это геттер, а не метод сервиса.на мой взгляд, обращение к методам, которые работают с хранилищем,  нужно спрятать внутри метода сервиса. например : filmService.deleteFilm(id);  а у же в классе сервиса в методе deleteFilm(id) сделать filmStorage().deleteFilm(id);  в контроллер не лезут лишние детали и читать просто.

2023-08-30 13:10 UTC, MaksSyrnev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        userService.getUserStorage().deleteUser(userId);
так же как и с фильмом , в контроллере, мне кажется не нужно  вытаскивать эти подробности, оставить только обращение к методу: userService.deleteUser(userId);

2023-08-30 13:10 UTC, MaksSyrnev commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/user/UserDbStorage.java
> +        if (!getUserById(userId).getEmail().isEmpty()) {
на мой взгляд лишняя проверка, лишняя нагрузка на базу

2023-08-30 13:10 UTC, MaksSyrnev commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/user/UserDbStorage.java
> +            log.debug("Пользователь не существует");
на мой взгляд, с точки зрения "удобства" обслуживания было бы удобно, если бы слой с логикой содержал всю обработку результатов и исключений, поэтому можно было бы перенести отсюда логгирование и выбросы исключений на уровень сервиса, а здесь возвращать возвращаемое значение от update, которое бы обрабатывалась на уровне сервиса.  Но не принципиально. - это "типа можно вот так " )

2023-08-30 21:08 UTC, Buriyone commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        filmService.getFilmStorage().deleteFilm(id);
можно добавить в сервисе прокидывалку до хранилища,  чтоб контроллер общался только с сервисом

2023-08-30 21:08 UTC, Buriyone commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        userService.getUserStorage().deleteUser(userId);
согласен

2023-08-30 21:08 UTC, Buriyone commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/film/FilmDbStorage.java
> +        if (!getByIdFilm(id).getName().isEmpty()) {
можно попробовать сразу отправлять запрос, в случае если произойдет ошибка поиска - пробросить 404?

2023-08-30 21:20 UTC, Chernosmaga commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        userService.getUserStorage().deleteUser(userId);
Ему бы, по хорошему, логику перенести всю в сервис, а в storage оставить только взаимодействие с БД. Там было бы читабельнее и код красивее, а сейчас чтоб получить друзей нужно обратить к сервису, а чтоб получить пользователей - к storage

2023-09-01 13:37 UTC, Elite-tea commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/film/FilmDbStorage.java
>              throw new NotFoundException(String.format("Фильма с id %d не существует", filmId));
Привет! тут как раз используются числа, у меня нет нигде описание строк, помоему)

2023-09-01 13:38 UTC, Elite-tea commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/film/FilmDbStorage.java
>              throw new NotFoundException(String.format("Фильма с id %d не существует", filmId));
А, кажется я понял о чем ты

2023-09-01 13:44 UTC, Elite-tea commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/film/FilmDbStorage.java
> +        if (!getByIdFilm(id).getName().isEmpty()) {
Отличный совет, try catch сработало!

2023-09-01 13:46 UTC, Elite-tea commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/film/FilmDbStorage.java
> +            jdbcTemplate.update("DELETE FROM film WHERE film_id = ?",id);
К вопросу выше, получилось решить через try catch, спасибо!

2023-09-01 13:47 UTC, Elite-tea commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/film/FilmDbStorage.java
> +            jdbcTemplate.update("DELETE FROM film WHERE film_id = ?",id);
Идея хорошая, но запрос используется один раз, и он очень короткий, хотя сама идя хранить запросы в константах имеют место к жизни

2023-09-01 13:49 UTC, Elite-tea commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        filmService.getFilmStorage().deleteFilm(id);
Отличное замечание, предлагаю оставить его на конечное ревью уже готовой ветки, что бы минимизировать конфликты

2023-09-01 13:49 UTC, Elite-tea commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        userService.getUserStorage().deleteUser(userId);
Как и написал выше, предлагаю сделать рефакторинг уже по факту слияния в develop

2023-09-01 14:04 UTC, Chernosmaga approved these changes

2023-09-01 14:23 UTC, ivanrud23 approved these changes

2023-09-01 19:27 UTC, merged